{{- if .Values.django.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.django.autoscaling.enabled }}
  replicas: {{ .Values.django.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "django.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "django.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: {{ include "django.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - {{ .Values.django.command | quote }}
          {{- include "django.envFrom" . | nindent 10 }}
          env:
            {{- include "django.redisEnv" . | nindent 12 }}
            {{- include "django.rabbitmqEnv" . | nindent 12 }}
            {{- include "django.postgresqlEnv" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          {{- if .Values.django.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.django.probes.liveness.path }}
              port: {{ .Values.image.containerPort }}
            initialDelaySeconds: {{ .Values.django.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.django.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.django.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.django.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.django.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.django.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.django.probes.readiness.path }}
              port: {{ .Values.image.containerPort }}
            initialDelaySeconds: {{ .Values.django.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.django.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.django.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.django.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.django.probes.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.django.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}