{{- if .Values.django.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "django.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "django.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}