{{- if and .Values.django.enabled .Values.django.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "django.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "django.fullname" . }}-backend
  minReplicas: {{ .Values.django.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.django.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.django.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.django.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.django.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.django.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}