{{- if .Values.jobs.migrations.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "django.fullname" . }}-migrations
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "django.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrations
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "django.serviceAccountName" . }}
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh", "-c" ]
          args:
            - {{ .Values.jobs.migrations.command | quote }}
          {{- include "django.envFrom" . | nindent 10 }}
          env:
            {{- include "django.redisEnv" . | nindent 12 }}
            {{- include "django.rabbitmqEnv" . | nindent 12 }}
            {{- include "django.postgresqlEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.jobs.migrations.resources | nindent 12 }}
{{- end }}