name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Debug Chart Directory
        run: |
          echo "Chart directory contents:"
          ls -la ./charts/django-app/
          echo "Chart.yaml contents:"
          cat ./charts/django-app/Chart.yaml

      - name: Build Helm Dependencies
        run: |
          echo "Adding bitnami repo..."
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

          echo "Building dependencies..."
          helm dependency update ./charts/django-app/

          echo "Checking if charts directory was created..."
          ls -la ./charts/django-app/

          if [ -d "./charts/django-app/charts" ]; then
            echo "Charts directory exists, listing contents:"
            ls -la ./charts/django-app/charts/
          else
            echo "Charts directory does not exist, creating it manually..."
            mkdir -p ./charts/django-app/charts
          fi

          echo "Checking for Chart.lock file..."
          if [ -f "./charts/django-app/Chart.lock" ]; then
            cat ./charts/django-app/Chart.lock
          else
            echo "Chart.lock file does not exist."
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
